INSERT INTO DEPT
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

INSERT INTO DEPT
VALUES(10, 'Accounts');

INSERT INTO DEPT
VALUES(NULL, 'TT');

UPDATE DEPT
SET DEPT_ID = 20
WHERE DEPT_NAME LIKE 'TT';

UPDATE DEPT
SET DEPT_ID = 30
WHERE DEPT_NAME LIKE 'Accounts';

SELECT * FROM DEPT;