CREATE TABLE EMP
    ( EMP_ID NUMBER(7),
    LAST_NAME VARCHAR(25) NOT NULL,
    FIRST_NAME VARCHAR2(25),
    DEPT_ID Number(7),
    CONSTRAINT  my_emp_id_pk PRIMARY KEY(EMP_ID),
    CONSTRAINT emp_dept_id_fk FOREIGN KEY (DEPT_ID)
    REFERENCES EMP (EMP_ID));

DESC EMP;

INSERT INTO EMP()
VALUES(101,'Sam','Sundar',10);

INSERT INTO EMP
VALUES(101,'Ram','Krishna',20);

INSERT INTO EMP
VALUES(102,'Gopi',null,40);

INSERT INTO EMP
VALUES(103,NULL,'Ram',20);