SELECT FIRST_NAME ||' '|| LAST_NAME ||' '|| q'[DEPARTMENT ID: ]' || DEPARTMENT_ID AS EMPLOYEE, SALARY AS "MONTHLY SALARY"
FROM EMPLOYEES
WHERE (SALARY > 5000 AND SALARY < 12000) AND (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50);